apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:      
      valueFiles:
        - values-prod.yaml
    # path to the folder with the YAML manifests
    path: .
    repoURL: https://github.com/winfriedbreuer/helm-nginx
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}
